application: przepisymm
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
- url: /favicon.ico
  static_files: m/favicon.ico
  upload: m/favicon.ico

- url: /robots.txt
  static_files: m/robots.txt
  upload: m/robots.txt

- url: /m/\d+/(.*)
  static_files: m/\1
  upload: m/(.*)

- url: /_media
  static_dir: kay/media

- url: /_kay/.*
  script: kay/main.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: kay/main.py
  login: admin

- url: /[a-z_-]+/cron/.*
  script: kay/main.py
  login: admin

- url: /stats.*
  script: lib/appstats/ui.py
  login: admin

- url: /.*
  script: kay/main.py

skip_files: |
  ^(.*/)?(
  (_backup/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.sh)|
  (.*\.pot)|
  (\..*)|
  (app\.yaml\.sample)|
  (index\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (manage\.py)|
  (^[^\/]+\/tests\.py$)|
  (^[^\/]+\/tests\/.*$)|
  (TODO)|
  (TODO\.pdf)|
  (README)|
  (README\.pdf)|
  (LICENSE)|
  (docs\/.*)|
  (kay\/management\/.*)|
  (-[a-z]+\/templates\/.*)|
  (media\/.*)|
  )$

